## Capitulo 3

### Projeto_data_Science

#### Scikit-Learn, avaliação de modelo e regressão logistica

In [1]:
# importando bibliotecas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import matplotlib as mpl
mpl.rcParams['figure.dpi'] = 400

In [2]:
# utilizando a versão limpa do arquivo csv que criamos anteriormente
df = pd.read_csv('Capitulo_1_arquivo_limpo.csv')

In [3]:
#Encontrando a proporção de classe positiva atrvé da média da variável de resposta do Dataset
# assim teremos também a taxa de inadimplência
df['default payment next month'].mean()

0.2217971797179718

In [4]:
# verificando o número de amostras em cada classe
df.groupby('default payment next month')['ID'].count()

default payment next month
0    20750
1     5914
Name: ID, dtype: int64

#### Podemos verificar acima que a variável alvo é 1 ou 0 e o percentual  de contas inadimplentes é de 22%. também verificamos o número de contas de cada classe executando uma operação 'groupby/count'.

# Implementando um modelo de Scikit-Learn

### Modelagem preditiva e regressão logística

In [5]:
# importando regressão logistica
from sklearn.linear_model import LogisticRegression

In [6]:
my_lr = LogisticRegression()

In [7]:
my_lr

LogisticRegression()

In [19]:
# Instanciando um modelo de regressão logistica com opções padrão

my_new_lr = LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True, 
            intercept_scaling=1, max_iter=100, multi_class='auto',
            n_jobs=None, penalty='l2', random_state=None, solver='warn',
            tol=0.0001, verbose=0, warm_start=False)

### Obs: nos parâmetros "multi_class" setado como "warn", eu estava obtendo erros de saída no encapsulamento das variáveis 'x e y'. Devido a isso também não seria possível executar o treinamento de modelos e realizar previsões.

### Foi necessário alterar os parâmetros para "auto" e então nosso modelo de regressão logistica funcionou perfeitamente!!

In [27]:
# Definindo opçoes e exibindo o estado atual do objeto de modelo.
# O objeto de modelo criado abaixo é um modelo treinado
# iremos usá-lo para fazer previsões para novas caracteristicas que o modelo ainda não não 'conhece'
my_new_lr.C = 0.1
my_new_lr.solver = 'liblinear'
my_new_lr

LogisticRegression(C=0.1, solver='liblinear')

In [21]:
# iremos usar as 10 primeiras linhas da caracteristica EDUCATION para teste
x = df['EDUCATION'][0:10].values.reshape(-1,1)
x

array([[2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [1],
       [2],
       [3],
       [3]], dtype=int64)

In [22]:
y = df['default payment next month'][0:10].values
y

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [23]:
my_new_lr.fit(x, y)

LogisticRegression(C=0.1, solver='liblinear')

In [24]:
new_x = df['EDUCATION'][10:20].values.reshape(-1,1)
new_x

array([[3],
       [1],
       [2],
       [2],
       [1],
       [3],
       [1],
       [1],
       [1],
       [3]], dtype=int64)

### A caracteristicas acima serão utilizadas na nossa variavel de previsão👆

In [25]:
# Criando nossas previsões👇
my_new_lr.predict(new_x)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [26]:
# Visualizando os valores reais correspondentes a essas previsões
df['default payment next month'][10:20].values

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 0], dtype=int64)

#### Resumo desse capitulo: Após obter os valores de nossas novas caracteristicas, chamamos o metodo "predict" no modelo treinado. Observe que o único argumento desse método é um conjunto de caracteristicas, isto é, um "X" que chamamos de 'new_x'

#### Nesse caso não foi fornecido nenhum "Y". Na verdade é para isso que serve a modelagem preditiva; você não sabe necessariamente o valor verdadeiro da variável de resposta, logo, tem de poder prevê-lo.

#### Também vimos que a saída do metodo "predict" sao as previsões do modelo para essas amostras. em seguida, comparamos essas previsôes com os valores reais da variavel de resposta no nosso dataset limpo.

#### Nosso modelo teve uma assertividade de 80%, o que parece bom para um projeto inicial. Este é um pequeno exemplo para me familiarizar com o scikit-learn e explorar mais esse método.

#### Veremos mais detalhes da avaliação de capacidade do modelo preditivo em breve...😉😉😉

### Fim do terceiro capitulo!!